-- Step 1: Switch to ACCOUNTADMIN to create the role and assign privileges
USE ROLE ACCOUNTADMIN;

-- Create role for the College of AI work
CREATE OR REPLACE ROLE CUSTOM_ML_REGISTRY_DEMO_ROLE;

-- Grant the role to your user
-- IMPORTANT: Replace '<user>' with your Snowflake username
GRANT ROLE CUSTOM_ML_REGISTRY_DEMO_ROLE TO USER <user>;

-- Create a dedicated database and warehouse
CREATE OR REPLACE DATABASE CUSTOM_ML_REGISTRY_DEMO_DB;
CREATE OR REPLACE SCHEMA DEMO_SCHEMA;
CREATE OR REPLACE WAREHOUSE CUSTOM_ML_REGISTRY_DEMO_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 300;

-- Grant necessary privileges to the role
GRANT USAGE ON WAREHOUSE CUSTOM_ML_REGISTRY_DEMO_WH TO ROLE CUSTOM_ML_REGISTRY_DEMO_ROLE;
GRANT ALL ON DATABASE CUSTOM_ML_REGISTRY_DEMO_DB TO ROLE CUSTOM_ML_REGISTRY_DEMO_ROLE;
GRANT ALL ON SCHEMA CUSTOM_ML_REGISTRY_DEMO_DB.public TO ROLE CUSTOM_ML_REGISTRY_DEMO_ROLE;
GRANT ALL ON SCHEMA CUSTOM_ML_REGISTRY_DEMO_DB.DEMO_SCHEMA TO ROLE CUSTOM_ML_REGISTRY_DEMO_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CUSTOM_ML_REGISTRY_DEMO_DB.public TO ROLE CUSTOM_ML_REGISTRY_DEMO_ROLE;

-- Granting create model registry for role
GRANT CREATE MODEL ON SCHEMA CUSTOM_ML_REGISTRY_DEMO_DB.DEMO_SCHEMA TO ROLE CUSTOM_ML_REGISTRY_DEMO_ROLE;